# Generated by Django 2.2.2 on 2019-06-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addName', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nameregister',
            old_name='question_text',
            new_name='name',
        ),
    ]
